### PR TITLE
Adding the basic skeleton for travis CI i.e travis.yml file

### PR DESCRIPTION
**Pull request by Vivek-Patil**

### CODE REVIEW

**Comment by Vivek-Patil** [comment]
1) Go to https://travis-ci.org/{username or org}/{repository}
2) Click the Status Image (a pop-up will appear)
3) Select a branch, then click the dropdown Image URL ▼ and set it to Markdown ▼.
4)Copy the markdown code that you can see, e.g: [Build Status](https://travis-ci.org/Linksys3966/akar.svg)](https://travis-ci.org/Linksys3966/akar
5) Copy Paste the code to your README.md
6) Git add, commit & push. Refresh github and you'll see the image now.

**Comment by missingfaktor** [comment]
Hi Vivek. Could you please update the URL to point to this repository? Also please move the build status sticker below the main header in the README. Thanks.

**Comment by Vivek-Patil** [comment]
Hi Rahul, the changes have been done, please review it once.

**Comment by missingfaktor** [comment]
This is great. Thanks, Vivek! Looking forward to more contributions in future. :+1:

**Pull request merged**
